apiVersion: v1
kind: Pod
metadata:
  name: kplabs-node-affinity-preffered
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: memory
            operator: In
            values:
            - high
            - medium          
  containers:
  - name: nginx
    image: nginx
