apiVersion: v1
kind: Pod
metadata:
    name: mywebserver
spec:
    containers:
    - name: container1
      image: nginx
    - name: container2
      image: busybox
      command: 
      - sleep
      - "3600"